### ISSUE TITLE
Useless comment here!! 

### ISSUE THREAD

**Issue by dharrisvi** [Corey56/RingLeader#11]
FAKE NEWS!! 

This really has nothing to do with the actual game. I'm just demonstrating my attempt at this. Between my repetitive computer crashes and now possession of a loaner, I can't really do much.

**Comment by dharrisvi** [comment]
@Corey56 Sir, I tried.

**Comment by sshamilton** [comment]
Well you did get a new issue opened.  Since this isn't a real issue with the system, I'll close it.  We are 6 hours ahead here in Lille France btw.

**Comment by sshamilton** [comment]
Well it looks like I don't have access to close this issue.

**Comment by Corey56** [comment]
Closing Fake News
